name: eslint check

# 定义触发CI工作流的事件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install pnpm
        run: npm install -g pnpm@8.15.5

      - name: Install Dependencies
        run: pnpm install

      - name: Run TypeCheck
        run: pnpm typecheck

      - name: Run ESLint
        run: pnpm lint
